# Generated by Django 5.2.7 on 2025-10-20 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formato1',
            fields=[
                ('folio', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='FOLIO PROYECTO')),
                ('introduccion', models.TextField(verbose_name='INTRODUCCIÓN')),
                ('justificacion', models.TextField(verbose_name='JUSTIFICACIÓN')),
                ('objetivo', models.TextField(verbose_name='OBJETIVO')),
                ('resumen', models.TextField(verbose_name='RESUMEN')),
            ],
            options={
                'verbose_name': 'Formato Inicial',
                'verbose_name_plural': 'Formatos Iniciales',
            },
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_representante', models.BooleanField(default=False, verbose_name='ES REPRESENTANTE')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.alumno')),
            ],
            options={
                'verbose_name': 'Participación en Proyecto',
                'verbose_name_plural': 'Participaciones en Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('folio', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='FOLIO DE PROYECTO')),
                ('titulo', models.CharField(max_length=255, verbose_name='TÍTULO DEL PROYECTO')),
                ('modalidad', models.CharField(choices=[('TRABAJO DE INVESTIGACIÓN', 'TRABAJO DE INVESTIGACIÓN'), ('MATERIALES EDUCATIVOS', 'MATERIALES EDUCATIVOS'), ('PROTOTIPO', 'PROTOTIPO'), ('REPORTE', 'REPORTE'), ('VINCULACIÓN SOCIAL', 'PROYECTOS DE VINCULACIÓN SOCIAL')], max_length=50, verbose_name='MODALIDAD')),
                ('nivel_competencia', models.CharField(max_length=20, verbose_name='VARIANTE DE MODALIDAD')),
                ('dictamen', models.CharField(max_length=50, verbose_name='DICTAMEN FINAL')),
                ('calendario_registro', models.CharField(max_length=10, verbose_name='CALENDARIO')),
                ('evidencia_url', models.URLField(max_length=500, verbose_name='URL EVIDENCIA PRINCIPAL')),
                ('protocolo_dictamen_url', models.URLField(max_length=500, verbose_name='URL PROTOCOLO DICTAMINADO')),
                ('evidencia_adicional_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL EVIDENCIA ADICIONAL')),
                ('asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.asesor', verbose_name='ASESOR ASIGNADO')),
                ('evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.evaluador', verbose_name='EVALUADOR ASIGNADO')),
                ('formato1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.formato1', verbose_name='DATOS FORMATO 1')),
                ('participantes', models.ManyToManyField(through='projects.Participacion', to='people.alumno', verbose_name='PARTICIPANTES')),
            ],
            options={
                'verbose_name': 'Proyecto Modular',
                'verbose_name_plural': 'Proyectos Modulares',
            },
        ),
        migrations.CreateModel(
            name='Prorroga',
            fields=[
                ('id_prorroga', models.AutoField(primary_key=True, serialize=False, verbose_name='ID DE PRÓRROGA')),
                ('justificacion', models.TextField(verbose_name='JUSTIFICACIÓN DE PRÓRROGA')),
                ('calendario_presentacion', models.CharField(max_length=10, verbose_name='CALENDARIO PARA PRESENTACIÓN')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proyecto', verbose_name='PROYECTO')),
            ],
            options={
                'verbose_name': 'Prórroga',
                'verbose_name_plural': 'Prórrogas',
            },
        ),
        migrations.AddField(
            model_name='participacion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.proyecto'),
        ),
        migrations.AlterUniqueTogether(
            name='participacion',
            unique_together={('proyecto', 'alumno')},
        ),
    ]
