# Generated by Django 5.2.7 on 2025-10-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='evidencia_adicional_url',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='variante',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='VARIANTE DE MODALIDAD'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='evidencia_url',
            field=models.URLField(max_length=500, null=True, verbose_name='URL EVIDENCIA PRINCIPAL'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nivel_competencia',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='MÓDULOS REGISTRADOS'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='protocolo_dictamen_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL PROTOCOLO DICTAMINADO'),
        ),
    ]
