# Generated by Django 5.2.7 on 2025-10-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_proyecto_evidencia_adicional_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='dictamen',
            field=models.CharField(default='PENDIENTE', max_length=50, verbose_name='DICTAMEN FINAL'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='evidencia_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL EVIDENCIA PRINCIPAL'),
        ),
    ]
