# Generated by Django 5.2.7 on 2025-10-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_proyecto_dictamen_alter_proyecto_evidencia_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='modalidad',
            field=models.CharField(choices=[('TRABAJO DE INVESTIGACIÓN', 'TRABAJO DE INVESTIGACIÓN'), ('MATERIALES EDUCATIVOS', 'MATERIALES EDUCATIVOS'), ('PROTOTIPO', 'PROTOTIPO'), ('REPORTE', 'REPORTE'), ('VINCULACIÓN SOCIAL', 'VINCULACIÓN SOCIAL')], max_length=50, verbose_name='MODALIDAD'),
        ),
    ]
