# Generated by Django 5.2.7 on 2025-10-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_proyecto_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='modalidad',
            field=models.CharField(choices=[('TRABAJO DE INVESTIGACION', 'TRABAJO DE INVESTIGACION'), ('MATERIALES EDUCATIVOS', 'MATERIALES EDUCATIVOS'), ('PROTOTIPO', 'PROTOTIPO'), ('REPORTE', 'REPORTE'), ('VINCULACION SOCIAL', 'VINCULACION SOCIAL')], max_length=50, verbose_name='MODALIDAD'),
        ),
    ]
